/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface EmojiPicker {
      'first': string;
      'last': string;
    }
  }

  interface HTMLEmojiPickerElement extends StencilComponents.EmojiPicker, HTMLStencilElement {}

  var HTMLEmojiPickerElement: {
    prototype: HTMLEmojiPickerElement;
    new (): HTMLEmojiPickerElement;
  };
  interface HTMLElementTagNameMap {
    'emoji-picker': HTMLEmojiPickerElement;
  }
  interface ElementTagNameMap {
    'emoji-picker': HTMLEmojiPickerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'emoji-picker': JSXElements.EmojiPickerAttributes;
    }
  }
  namespace JSXElements {
    export interface EmojiPickerAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
